# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plist_concerts', '0002_artists_timekeeper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artists',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='timekeeper',
            name='first_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='timekeeper',
            name='last_date',
            field=models.DateField(),
        ),
    ]
