# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-27 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plist_concerts', '0003_auto_20170925_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artists',
            name='date',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='timekeeper',
            name='first_date',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='timekeeper',
            name='last_date',
            field=models.CharField(max_length=10),
        ),
    ]
