# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-11 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plist_concerts', '0005_auto_20171004_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_update',
            field=models.CharField(default=b'10102017', max_length=10),
        ),
    ]
