# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-06 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plist_concerts', '0007_auto_20180105_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='timekeeper',
            name='last_accessed',
            field=models.CharField(default=b'05052018', max_length=10),
        ),
    ]
